### ISSUE TITLE
Invalid Discord server link

### ISSUE THREAD

**Issue by c4tgrl** [femdevs/.github#1]
https://github.com/femdevs/.github/blob/8dcca41044e58d74ae35c8a4fdc6b82ad90e1e5e/profile/README.md?plain=1#L15

https://kawaii.mizu.cafe/meow-uwu-nya-:3/gXVrx91HuApWwHfwk5tUwq.jpg

I can't join :sob:

**Comment by therealbenpai** [comment]
@mldkyt should be fixed now

new link: https://discord.gg/75BcNV5y5s
